# -*- coding: utf-8 -*-
"""Balanceador de Carga Web

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11LRug9HcNfcXmIWTxjAd15pJLWe8hjJv
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import re
import io

# ==========================================
# CONFIGURACIÓN DE PÁGINA
# ==========================================
st.set_page_config(page_title="Optimizador de Carga de Mantenimiento", layout="wide")
st.title("Motor Heurístico de Balance de HH")

# ==========================================
# 1. TRANSFORMADOR DEFENSIVO (PARSER)
# ==========================================
@st.cache_data
def load_and_clean_data(uploaded_file):
    # Leer archivo ignorando la fila 0 (descripciones) si es CSV o Excel
    try:
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file, header=1)
        else:
            df = pd.read_excel(uploaded_file, header=1)
    except Exception as e:
        st.error(f"Error en la ingesta: {e}")
        return pd.DataFrame()

    # Limpieza de espacios en columnas
    df.columns = [str(c).strip() for c in df.columns]

    # Validaciones y Rellenos de Seguridad
    if 'Criticality' in df.columns:
        df['Criticality'] = pd.to_numeric(df['Criticality'], errors='coerce').fillna(1).astype(int)

    if 'Maximum_Tolerance_Value' in df.columns:
        df['Maximum_Tolerance_Value'] = pd.to_numeric(df['Maximum_Tolerance_Value'], errors='coerce').fillna(0).astype(int)

    if 'Work' in df.columns:
        df['Work'] = pd.to_numeric(df['Work'], errors='coerce').fillna(0.0)

    if 'Frequency_Value' in df.columns:
        df['Frequency_Value'] = pd.to_numeric(df['Frequency_Value'], errors='coerce').fillna(52)

    # Conversión de Horómetros a Semanas
    df['Semanas_Intervalo'] = df['Frequency_Value']
    if 'Frequency_Unit' in df.columns and 'Average_Daily_Usage' in df.columns:
        mask_horas = df['Frequency_Unit'].str.lower().str.contains('hour', na=False)
        adu = pd.to_numeric(df['Average_Daily_Usage'], errors='coerce').fillna(24) # Asume 24h si está vacío
        df.loc[mask_horas, 'Semanas_Intervalo'] = (df.loc[mask_horas, 'Frequency_Value'] / adu) / 7

    df['Semanas_Intervalo'] = np.maximum(1, df['Semanas_Intervalo'].round().astype(int))

    return df

# ==========================================
# 2. MOTOR HEURÍSTICO (CORE)
# ==========================================
def run_heuristic_engine(df, anchor_seeds):
    HORIZONTE = 156

    # Calendario de Carga: {especialidad: array[156]}
    especialidades = df['Labour'].dropna().unique()
    calendario = {esp: np.zeros(HORIZONTE) for esp in especialidades}

    # Matriz de resultados (El Output para SAP)
    output_records = []

    # --- ORDENAMIENTO (Rocas vs Arena) ---
    df_sorted = df.sort_values(
        by=['Criticality', 'Maximum_Tolerance_Value', 'Work'],
        ascending=[False, True, False]
    )

    for idx, row in df_sorted.iterrows():
        esp = row['Labour']
        if pd.isna(esp): continue

        hh = row['Work']
        frecuencia = row['Semanas_Intervalo']
        tolerancia = row['Maximum_Tolerance_Value']
        anchor_id = str(row.get('Shutdown_Anchor_ID', '')).strip()
        op_mode = str(row.get('Operation Mode', '')).strip().upper()

        semanas_ejecucion = []
        tipo_ejecucion = 'Internal'

        # FASE 1: BLOQUE MONOLÍTICO (PARADAS DE PLANTA)
        if anchor_id and anchor_id.lower() != 'nan':
            # Extraer intervalo del nombre (ej. "3M" -> 13 semanas, "6M" -> 26, "1Y" -> 52)
            match = re.search(r'(\d+)([YMym])', anchor_id)
            if match:
                val, unit = int(match.group(1)), match.group(2).upper()
                intervalo_parada = val * 13 if unit == 'M' else val * 52
            else:
                intervalo_parada = 52 # Fallback

            sem_inicio = anchor_seeds.get(anchor_id, 1) - 1 # 0-indexed

            # Proyectar eventos en el horizonte
            semanas_teoricas = [sem_inicio + i * intervalo_parada for i in range(HORIZONTE // intervalo_parada + 1)]
            semanas_ejecucion = [s for s in semanas_teoricas if s < HORIZONTE]
            tipo_ejecucion = 'Contractor_Major' # Por defecto asume apoyo externo en paradas mayores

        # FASE 2 & 3: BLOQUES MÓVILES Y MASILLA LÍQUIDA
        else:
            # Buscar el "Offset" base que genere la menor carga promedio
            mejor_offset = 0
            menor_carga_promedio = float('inf')

            for offset_candidato in range(frecuencia):
                semanas_prueba = [offset_candidato + i * frecuencia for i in range(HORIZONTE // frecuencia + 1) if offset_candidato + i * frecuencia < HORIZONTE]
                carga_promedio = np.mean([calendario[esp][s] for s in semanas_prueba]) if semanas_prueba else 0

                if carga_promedio < menor_carga_promedio:
                    menor_carga_promedio = carga_promedio
                    mejor_offset = offset_candidato

            # Aplicar micro-desfasajes usando Tolerancia Máxima para esquivar picos locales
            semanas_base = [mejor_offset + i * frecuencia for i in range(HORIZONTE // frecuencia + 1) if mejor_offset + i * frecuencia < HORIZONTE]

            for s_base in semanas_base:
                rango_min = max(0, s_base - tolerancia)
                rango_max = min(HORIZONTE - 1, s_base + tolerancia)

                # Encontrar el valle más profundo en este rango local
                cargas_rango = [calendario[esp][s] for s in range(rango_min, rango_max + 1)]
                semana_optima = rango_min + np.argmin(cargas_rango)
                semanas_ejecucion.append(semana_optima)

        # Grabar la tarea en el calendario y en el registro final
        for s_final in semanas_ejecucion:
            calendario[esp][s_final] += hh

            output_records.append({
                'Maintenance_Item_Tag': row.get('Location_Code', 'N/A'),
                'Work_Center': esp,
                'Planned_Date_Week': s_final + 1, # Volver a 1-indexed para SAP
                'Estimated_Work_Hours': hh,
                'Headcount_Required': row.get('Labour_Required', 1),
                'Operation_Mode': op_mode,
                'Shutdown_Code': anchor_id if anchor_id and anchor_id.lower() != 'nan' else '',
                'Execution_Type': tipo_ejecucion
            })

    df_output = pd.DataFrame(output_records)
    return calendario, df_output

# ==========================================
# 3. INTERFAZ Y FLUJO PRINCIPAL
# ==========================================
st.sidebar.header("1. Ingesta de Datos")
uploaded_file = st.sidebar.file_uploader("Sube la Plantilla de Input (CSV/Excel)", type=['csv', 'xlsx'])

if uploaded_file:
    df_raw = load_and_clean_data(uploaded_file)

    if df_raw.empty:
        st.stop()

    st.sidebar.success(f"{len(df_raw)} Tareas validadas.")

    # Extracción de Paradas Dinámica (RegEx)
    anchors_detectados = [a for a in df_raw['Shutdown_Anchor_ID'].unique() if pd.notna(a) and str(a).strip().lower() != 'nan']
    anchor_seeds = {}

    if anchors_detectados:
        st.sidebar.header("2. Semillas de Paradas Mayores")
        for anchor in anchors_detectados:
            # Detectar si es trimestral, semestral, etc para sugerir inicio
            seed_default = 1
            if '3M' in anchor: seed_default = 13
            elif '6M' in anchor: seed_default = 26
            elif '1Y' in anchor: seed_default = 52

            anchor_seeds[anchor] = st.sidebar.number_input(f"Semana de inicio para {anchor}", min_value=1, max_value=52, value=seed_default)

    st.sidebar.header("3. Umbrales de Capacidad (Financieros)")
    personal_propio = st.sidebar.slider("Headcount Propio Total", 5, 100, 20)
    horas_efectivas = st.sidebar.slider("Wrench Time (HH netas/sem)", 10.0, 40.0, 15.0)
    tarifa_interna = st.sidebar.number_input("Tarifa Interna ($/hora)", value=30.0)
    tarifa_externa = st.sidebar.number_input("Tarifa Contratista ($/hora)", value=80.0)

    capacidad_semanal_total = personal_propio * horas_efectivas

    if st.sidebar.button("Ejecutar Optimización", type="primary"):
        with st.spinner('Aplanando curva en el horizonte de 156 semanas...'):
            calendario_dict, df_output = run_heuristic_engine(df_raw, anchor_seeds)

        st.success("Heurística completada.")

        # --- CÁLCULO FINANCIERO Y ÓPTIMO ---
        # Consolidar horas semanales totales en el año 1 (Semanas 0 a 51)
        carga_total_semanal = np.zeros(156)
        for esp, carga in calendario_dict.items():
            carga_total_semanal += carga

        carga_year_1 = carga_total_semanal[0:52]

        # Simulación de Derivada Mínima para Costo Óptimo
        costos_simulados = []
        for hc_test in range(1, 101):
            cap_test = hc_test * horas_efectivas
            costo_int = sum([min(c, cap_test) for c in carga_year_1]) * tarifa_interna
            costo_ext = sum([max(0, c - cap_test) for c in carga_year_1]) * tarifa_externa
            costos_simulados.append(costo_int + costo_ext)

        hc_optimo = np.argmin(costos_simulados) + 1
        ahorro_potencial = (sum([min(c, capacidad_semanal_total) for c in carga_year_1]) * tarifa_interna +
                           sum([max(0, c - capacidad_semanal_total) for c in carga_year_1]) * tarifa_externa) - min(costos_simulados)

        # --- PANEL DE KPIS ---
        cols = st.columns(4)
        hh_anuales = np.sum(carga_year_1)

        # KPI 1: Costo con HC Actual
        costo_actual_int = sum([min(c, capacidad_semanal_total) for c in carga_year_1]) * tarifa_interna
        costo_actual_ext = sum([max(0, c - capacidad_semanal_total) for c in carga_year_1]) * tarifa_externa

        cols[0].metric("Demanda Anual Total", f"{hh_anuales:,.0f} HH")
        cols[1].metric("Costo Total Anual (Simulado)", f"${(costo_actual_int + costo_actual_ext):,.0f}")
        cols[2].metric("Ociosidad de Personal", f"{(1 - (hh_anuales / (capacidad_semanal_total * 52))) * 100:.1f}%" if hh_anuales < (capacidad_semanal_total * 52) else "0%")

        # KPI Estrella
        cols[3].markdown(f"""
            <div style="background-color: #d4edda; padding: 10px; border-radius: 5px; text-align: center; border: 1px solid #c3e6cb;">
                <h4 style="color: #155724; margin:0;">Headcount Propio Óptimo</h4>
                <h2 style="color: #155724; margin:0; font-size: 32px;">{hc_optimo} Técnicos</h2>
                <span style="color: #155724;">Minimiza el Costo Total Anual</span>
            </div>
        """, unsafe_allow_html=True)

        # --- VISUALIZACIÓN (HORIZONTE RODANTE) ---
        st.subheader("Carga Dinámica de Mantenimiento (Horizonte Rodante)")
        vista_year = st.radio("Seleccione Año de Visualización:", ["Año 1 (Semanas 1-52)", "Año 2 (Semanas 53-104)", "Año 3 (Semanas 105-156)"])

        offset_grafico = 0
        if "Año 2" in vista_year: offset_grafico = 52
        if "Año 3" in vista_year: offset_grafico = 104

        fig = go.Figure()

        # Barras apiladas por especialidad
        for esp, carga in calendario_dict.items():
            fig.add_trace(go.Bar(
                x=list(range(1, 53)),
                y=carga[offset_grafico : offset_grafico+52],
                name=esp
            ))

        # Línea de Capacidad Dura (Constante)
        fig.add_trace(go.Scatter(
            x=list(range(1, 53)),
            y=[capacidad_semanal_total] * 52,
            mode='lines',
            name=f'Capacidad Propia Máxima ({personal_propio} Tec)',
            line=dict(color='red', width=3, dash='dash')
        ))

        fig.update_layout(
            barmode='stack',
            xaxis_title="Semana del Año",
            yaxis_title="Horas Hombre Demandadas",
            legend_title="Especialidades",
            hovermode="x unified",
            template="plotly_white"
        )
        st.plotly_chart(fig, use_container_width=True)

        # --- DESCARGA PARA ERP (SAP S/4 PM) ---
        st.subheader("Entregable Estructurado")
        st.dataframe(df_output.head(10)) # Muestra previa

        csv_buffer = io.StringIO()
        df_output.to_csv(csv_buffer, index=False)
        st.download_button(
            label="Descargar Plan Optimizado para SAP (CSV)",
            data=csv_buffer.getvalue(),
            file_name="Plan_Mantenimiento_SAP.csv",
            mime="text/csv",
            type="primary"
        )

else:
    st.info("Sube la plantilla por el panel lateral para iniciar el motor heurístico.")